### ISSUE TITLE
Your local content (eg.level data) does not match the content on the server.

### ISSUE THREAD

**Issue by keku645** [BF3RM/MapLoader#5]
This happens when you have a save with modified/removed vanilla assets, when the map is reloaded, then you leave the server and join back in this error prompts.

It wont happen if you choose any other mode on the same map.

Tested on many maps to confirm it.

![Vu Screenshot 2021 07 02 - 04 08 40 90](https://user-images.githubusercontent.com/36018654/124210792-564dac00-daec-11eb-82cd-b649aca490d5.png)

**Comment by keku645** [comment]
Closed because I've forgotten it was already in maped branch.

**Comment by keku645** [comment]
reopened again due its maploader related.

**Comment by FoolHen** [comment]
@keku645 i cant reproduce, can you create a simple example? (without loading bundles or external mods)

**Comment by keku645** [comment]
I did it again with no mods and anything.

On kiasar Conquest Large

1- Remove any asset in maped.
2- Restart the round on the same map and mode, from pre-round to round also works.
3- Once the level loaded again, leave the server and join back, the error will pop up.

**Comment by FoolHen** [comment]
Use ``-skipchecksum`` server parameter https://docs.veniceunleashed.net/general/args/#server-arguments
